# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_hashes',
            name='file',
            field=models.BinaryField(default=None),
        ),
    ]
