# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 19:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileUpload', '0002_file_hashes_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_hashes',
            name='user',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
